image: ocaml/opam:debian

stages:
  - test

.install-utils: &install-utils
  - opam switch
  - opam install dune
  - eval $(opam env)

test:
  stage: test
  before_script: *install-utils
  script:
    - make test
